/*
 * NVIC_Port.h
 *
 *  Created on: Mar 9, 2021
 *      Author: Esraa Abdelnaby
 */

#ifndef NVIC_PORT_H_
#define NVIC_PORT_H_

#define IMP_BITS 4

typedef enum{
	  _IRQn_NMI			          = -14,
	  _IRQn_MemoryManagement       = -12,
	  _IRQn_BusFault               = -11,
	  _IRQn_UsageFault             = -10,
	  _IRQn_SVCall                 = -5,
	  _IRQn_DebugMonitor           = -4,
	  _IRQn_PendSV                 = -2,
	  _IRQn_SysTick                = -1,
	  _IRQn_WWDG                   = 0,
	  _IRQn_PVD                    = 1,
	  _IRQn_TAMP_STAMP             = 2,
	  _IRQn_RTC_WKUP               = 3,
	  _IRQn_FLASH                  = 4,
	  _IRQn_RCC                    = 5,
	  _IRQn_EXTI0                  = 6,
	  _IRQn_EXTI1                  = 7,
	  _IRQn_EXTI2                  = 8,
	  _IRQn_EXTI3                  = 9,
	  _IRQn_EXTI4                  = 10,
	  _IRQn_DMA1_Stream0           = 11,
	  _IRQn_DMA1_Stream1           = 12,
	  _IRQn_DMA1_Stream2           = 13,
	  _IRQn_DMA1_Stream3           = 14,
	  _IRQn_DMA1_Stream4           = 15,
	  _IRQn_DMA1_Stream5           = 16,
	  _IRQn_DMA1_Stream6           = 17,
	  _IRQn_ADC                    = 18,
	  _IRQn_CAN1_TX                = 19,
	  _IRQn_CAN1_RX0               = 20,
	  _IRQn_CAN1_RX1               = 21,
	  _IRQn_CAN1_SCE               = 22,
	  _IRQn_EXTI9_5                = 23,
	  _IRQn_TIM1_BRK_TIM9          = 24,
	  _IRQn_TIM1_UP_TIM10          = 25,
	  _IRQn_TIM1_TRG_COM_TIM11     = 26,
	  _IRQn_TIM1_CC                = 27,
	  _IRQn_TIM2                   = 28,
	  _IRQn_TIM3                   = 29,
	  _IRQn_TIM4                   = 30,
	  _IRQn_I2C1_EV                = 31,
	  _IRQn_I2C1_ER                = 32,
	  _IRQn_I2C2_EV                = 33,
	  _IRQn_I2C2_ER                = 34,
	  _IRQn_SPI1                   = 35,
	  _IRQn_SPI2                   = 36,
	  _IRQn_USART1                 = 37,
	  _IRQn_USART2                 = 38,
	  _IRQn_USART3                 = 39,
	  _IRQn_EXTI15_10              = 40,
	  _IRQn_RTC_Alarm              = 41,
	  _IRQn_OTG_FS_WKUP            = 42,
	  _IRQn_TIM8_BRK_TIM12         = 43,
	  _IRQn_TIM8_UP_TIM13          = 44,
	  _IRQn_TIM8_TRG_COM_TIM14     = 45,
	  _IRQn_TIM8_CC                = 46,
	  _IRQn_DMA1_Stream7           = 47,
	  _IRQn_FSMC                   = 48,
	  _IRQn_SDIO                   = 49,
	  _IRQn_TIM5                   = 50,
	  _IRQn_SPI3                   = 51,
	  _IRQn_UART4                  = 52,
	  _IRQn_UART5                  = 53,
	  _IRQn_TIM6_DAC               = 54,
	  _IRQn_TIM7                   = 55,
	  _IRQn_DMA2_Stream0           = 56,
	  _IRQn_DMA2_Stream1           = 57,
	  _IRQn_DMA2_Stream2           = 58,
	  _IRQn_DMA2_Stream3           = 59,
	  _IRQn_DMA2_Stream4           = 60,
	  _IRQn_ETH                    = 61,
	  _IRQn_ETH_WKUP               = 62,
	  _IRQn_CAN2_TX                = 63,
	  _IRQn_CAN2_RX0               = 64,
	  _IRQn_CAN2_RX1               = 65,
	  _IRQn_CAN2_SCE               = 66,
	  _IRQn_OTG_FS                 = 67,
	  _IRQn_DMA2_Stream5           = 68,
	  _IRQn_DMA2_Stream6           = 69,
	  _IRQn_DMA2_Stream7           = 70,
	  _IRQn_USART6                 = 71,
	  _IRQn_I2C3_EV                = 72,
	  _IRQn_I2C3_ER                = 73,
	  _IRQn_OTG_HS_EP1_OUT         = 74,
	  _IRQn_OTG_HS_EP1_IN          = 75,
	  _IRQn_OTG_HS_WKUP            = 76,
	  _IRQn_OTG_HS                 = 77,
	  _IRQn_DCMI                   = 78,
	  _IRQn_HASH_RNG               = 80,
	  _IRQn_FPU                    = 81,
}IRQn_t;


#endif /* NVIC_PORT_H_ */
